SET NAMES utf8;

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO,ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0;

CREATE DATABASE IF NOT EXISTS `paradise` DEFAULT CHARACTER SET utf8;

USE `paradise`;

/*Table structure for table `Cliente` */

DROP TABLE IF EXISTS `Cliente`;

CREATE TABLE `Cliente` (
  `CLIENID` INT NOT NULL AUTO_INCREMENT,
  `CLIENOME` VARCHAR(300) NOT NULL,
  `CLIENENDERE` VARCHAR(300),
  `CLIENUMERO` VARCHAR(20),
  `CLIENASCIS` DATE,
  `CLIENEMAIL` VARCHAR(256) NOT NULL,
  `CLIENSENHA` VARCHAR(40) NOT NULL,
  PRIMARY KEY (`CLIENID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `Fornecedor` */

DROP TABLE IF EXISTS `Fornecedor`;

CREATE TABLE `Fornecedor` (
  `FORNID` INT NOT NULL AUTO_INCREMENT,
  `FORNNOME` VARCHAR(256),
  `FORNENDE` VARCHAR(300),
  `FORNNUME` VARCHAR(10),
  `FORNEMAIL` VARCHAR(256),
  PRIMARY KEY (`FORNID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `Produto` */

DROP TABLE IF EXISTS `Produto`;

CREATE TABLE `Produto` (
  `PRODID` INT NOT NULL AUTO_INCREMENT,
  `PRODNOME` VARCHAR(200),
  `PRODESC` TEXT(300),
  `PRODPRE` DECIMAl(4,2),
  `PRODQTD` INT,
  `PRODFOTO` VARCHAR(500),
  `FORNID` INT,
  PRIMARY KEY (`PRODID`),
  KEY `fk_forn_id` (`FORNID`),
  CONSTRAINT `fk_forn_id` FOREIGN KEY (`FORNID`) REFERENCES `Fornecedor` (`FORNID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `Funcionario` */

DROP TABLE IF EXISTS `Funcionario`;

CREATE TABLE `Funcionario` (
  `FUNCID` INT NOT NULL AUTO_INCREMENT,
  `FUNCNOME` VARCHAR(250),
  `FUNCENDERE` VARCHAR(300),
  `FUNCNUMERO` VARCHAR(10),
  `FUNCEMAIL` VARCHAR(256),
  `FUNCSENHA` VARCHAR(40),
  `FUNUSER` Varchar(40),
  `FUNUSUARIO` TINYINT,
  PRIMARY KEY (`FUNCID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `Venda` */

DROP TABLE IF EXISTS `Venda`;

CREATE TABLE `Venda` (
  `VENID` INT NOT NULL AUTO_INCREMENT,
  `VENDATA` DATE NOT NULL,
  `VENAGENDAMENTO` DATE NOT NULL,
  `VENRETIRADA` VARCHAR(10) NOT NULL,
  `CLIENID` INT,
  PRIMARY KEY (`VENID`),
  KEY `fk_clien_id` (`CLIENID`),
  CONSTRAINT `fk_clien_id` FOREIGN KEY (`CLIENID`) REFERENCES `Cliente` (`CLIENID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

/*Table structure for table `Itens` */

DROP TABLE IF EXISTS `Itens`;

CREATE TABLE `Itens` (
  `ITID` INT NOT NULL AUTO_INCREMENT,
  `VENID` INT NOT NULL,
  `PRODID` INT NOT NULL,
  PRIMARY KEY (`ITID`),
  KEY `fk_ven_id` (`VENID`),
  KEY `fk_prod_id` (`PRODID`),
  CONSTRAINT `fk_ven_id` FOREIGN KEY (`VENID`) REFERENCES `Venda` (`VENID`),
  CONSTRAINT `fk_prod_id` FOREIGN KEY (`PRODID`) REFERENCES `Produto` (`PRODID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
